site_name: AY-3-8910 Sound Chip Wrapper
site_description: Python wrapper for the AY-3-8910 and AY-3-8912 sound chip emulators.
site_url: https://devfred78.github.io/ay8910
repo_url: https://github.com/devfred78/ay8910
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - API Reference: reference.md
  - Contributing: contribute.md
  - License: license.md
